import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Section } from "@/components/ui/section";
import { Button } from "@/components/ui/button";
import { DevelopmentShell } from "@/components/development/development-shell";

export const metadata: Metadata = { title: "Generate digest · Development OS" };
export const dynamic = "force-dynamic";

export default function NewDigestPage() {
  return (
    <DevelopmentShell>
      <PageHeader
        title="Generate digest"
        breadcrumbs={[
          { label: "Development OS", href: "/development-os" },
          { label: "Digests", href: "/development-os/digests" },
          { label: "Generate" },
        ]}
        description="On-demand digests are generated by triggering the monthly cron job manually."
        actions={
          <Button asChild variant="secondary">
            <Link href="/development-os/digests">
              <ArrowLeft className="w-4 h-4" strokeWidth={1.75} />
              Back
            </Link>
          </Button>
        }
      />
      <Section title="How to generate">
        <p className="text-sm leading-relaxed">
          Open <Link href="/dashboard/jobs" className="underline">Jobs</Link>{" "}
          and run <code className="bg-muted/40 px-1 rounded">dev_os_executive_digest_monthly</code>.
          A new digest is created as <code>draft</code>, then editable here.
        </p>
        <p className="text-sm leading-relaxed mt-2">
          The cron is also scheduled at <code>0 6 1 * *</code> (1st of each month, 06:00 UTC).
          Idempotent — same month re-runs will not duplicate.
        </p>
      </Section>
    </DevelopmentShell>
  );
}
