import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Card } from "@/components/dashboard/primitives";
import { DevelopmentShell } from "@/components/development/development-shell";

export const metadata: Metadata = { title: "Generate digest · Development OS" };
export const dynamic = "force-dynamic";

export default function NewDigestPage() {
  return (
    <DevelopmentShell>
      <div className="page-header">
        <div className="left">
          <div className="crumb">
            <Link href="/development-os">Development OS</Link> /{" "}
            <Link href="/development-os/digests">Digests</Link> /{" "}
            <span>Generate</span>
          </div>
          <h1>Generate digest</h1>
          <p className="text-[13px] text-ink-3 mt-2 max-w-[680px]">
            On-demand digests are generated by triggering the monthly cron job manually.
          </p>
        </div>
        <div className="actions">
          <Link
            href="/development-os/digests"
            className="btn btn-secondary btn-sm"
          >
            <ArrowLeft className="w-4 h-4" strokeWidth={1.75} />
            Back
          </Link>
        </div>
      </div>
      <div>
        <div className="label mb-2.5">How to generate</div>
        <Card padding="default">
          <p className="text-sm leading-relaxed">
            Open <Link href="/dashboard/jobs" className="underline">Jobs</Link>{" "}
            and run <code className="bg-muted/40 px-1 rounded">dev_os_executive_digest_monthly</code>.
            A new digest is created as <code>draft</code>, then editable here.
          </p>
          <p className="text-sm leading-relaxed mt-2">
            The cron is also scheduled at <code>0 6 1 * *</code> (1st of each month, 06:00 UTC).
            Idempotent — same month re-runs will not duplicate.
          </p>
        </Card>
      </div>
    </DevelopmentShell>
  );
}
