-- =============================================================================
-- 0076 — Development OS · Stage 6.P1.A — Channel Manager Foundation
--
-- 2 new tables:
--   - channel_connections   per-(organization, villa, channel) connection
--                           record. Holds encrypted credentials, rate-plan +
--                           amenity + policy mapping JSONB, last-sync state,
--                           commercial fields (commission %, payment model).
--                           Encryption envelope: STAY_LINK_KMS_SECRET (same as
--                           guest-stay tokens + bulk_import oauth_connections).
--   - channel_sync_log      per-attempt audit row (inventory push, rates push,
--                           amenities push, reservations pull, webhook receive).
--                           Tracks duration, records counts, api_calls_count
--                           for cost tracking, error details JSONB on failure.
--
-- RLS: per-org isolation via is_in_user_organization() (Stage 5.J helper).
-- Idempotent.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1) channel_connections
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "channel_connections" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" UUID NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "villa_id" UUID NOT NULL REFERENCES "villas"("id") ON DELETE CASCADE,

  "channel" TEXT NOT NULL CHECK ("channel" IN (
    'booking_com', 'airbnb', 'trip_com', 'agoda',
    'expedia', 'vrbo', 'hotels_com', 'direct'
  )),

  -- External identifiers — channel-specific. `external_property_id` is the
  -- canonical "this is the property on their side" handle (hotel_id on
  -- Booking, listing_id on Airbnb, hotel_id on Trip, etc.). `external_room_id`
  -- is set when the channel models rooms separately from properties (most
  -- channels do — a villa is one room within one property).
  "external_property_id" TEXT NOT NULL,
  "external_room_id" TEXT,
  "external_rate_plan_ids" TEXT[],

  "status" TEXT NOT NULL DEFAULT 'pending' CHECK ("status" IN (
    'pending', 'connecting', 'active', 'paused', 'error', 'archived'
  )),

  -- Credentials JSONB: encrypted at the application layer using
  -- STAY_LINK_KMS_SECRET (per-channel discriminated union — see
  -- docs/CHANNEL-CREDENTIALS-FORMAT.md once P1.B lands).
  -- Stored as JSONB rather than TEXT so partial reads can pull
  -- non-secret metadata (e.g. environment) without decrypting the
  -- secret blob — encryption happens on the secret-bearing fields.
  "credentials" JSONB,

  -- Webhook secret per connection — generated by the channel after
  -- registration. Used by webhook handlers to verify HMAC signatures.
  "webhook_secret" TEXT,

  -- Sync configuration: per-rate-plan + per-amenity + per-policy mapping
  -- JSONB. Defaults to empty so a connection can move to `active` before
  -- the operator finishes mapping; pushes will skip unmapped fields and
  -- log a warning rather than fail the whole sync.
  "rate_plan_mapping" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "amenity_mapping" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "policy_mapping" JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Sync state: last attempt per direction. Status values mirror
  -- channel_sync_log.status so the UI can render the latest result
  -- without a join. Updated by the sync cron after every attempt.
  "last_inventory_sync_at" TIMESTAMPTZ,
  "last_inventory_sync_status" TEXT CHECK (
    "last_inventory_sync_status" IS NULL OR
    "last_inventory_sync_status" IN ('pending', 'running', 'success', 'partial', 'failed')
  ),
  "last_inventory_sync_error" TEXT,

  "last_reservation_sync_at" TIMESTAMPTZ,
  "last_reservation_sync_status" TEXT CHECK (
    "last_reservation_sync_status" IS NULL OR
    "last_reservation_sync_status" IN ('pending', 'running', 'success', 'partial', 'failed')
  ),
  "last_reservation_sync_error" TEXT,

  -- Commercial fields. `channel_commission_pct` is the operator's
  -- recorded commission rate (e.g. 15.00 for Booking.com's typical
  -- 15%) used to compute expected commission per reservation.
  -- `channel_payment_model` reflects who collects the guest's payment:
  --   - 'channel'        — channel collects + remits net to property
  --   - 'merchant'       — channel collects + remits via virtual card
  --   - 'hotel_collect'  — property collects directly from guest
  "channel_commission_pct" NUMERIC(5,2),
  "channel_payment_model" TEXT CHECK (
    "channel_payment_model" IS NULL OR
    "channel_payment_model" IN ('channel', 'merchant', 'hotel_collect')
  ),

  -- Audit
  "connected_by" UUID REFERENCES "app_users"("id") ON DELETE SET NULL,
  "connected_at" TIMESTAMPTZ,
  "archived_at" TIMESTAMPTZ,
  "archive_reason" TEXT,

  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One connection per (org, villa, channel) — re-connecting overwrites
  -- the existing row rather than creating duplicates.
  CONSTRAINT "channel_connections_org_villa_channel_unique"
    UNIQUE ("organization_id", "villa_id", "channel")
);

CREATE INDEX IF NOT EXISTS "channel_connections_villa_idx"
  ON "channel_connections"("villa_id");
CREATE INDEX IF NOT EXISTS "channel_connections_status_idx"
  ON "channel_connections"("status");
CREATE INDEX IF NOT EXISTS "channel_connections_channel_idx"
  ON "channel_connections"("channel");
-- Partial index for the cron scanner — only active connections need to
-- be scanned for sync. Saves a full-table scan as the table grows.
CREATE INDEX IF NOT EXISTS "channel_connections_active_idx"
  ON "channel_connections"("status", "last_inventory_sync_at")
  WHERE "status" = 'active';

CREATE OR REPLACE FUNCTION "channel_connections_set_updated_at"()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "trg_channel_connections_updated_at" ON "channel_connections";
CREATE TRIGGER "trg_channel_connections_updated_at"
  BEFORE UPDATE ON "channel_connections"
  FOR EACH ROW EXECUTE FUNCTION "channel_connections_set_updated_at"();

-- -----------------------------------------------------------------------------
-- 2) channel_sync_log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "channel_sync_log" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" UUID NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "channel_connection_id" UUID NOT NULL REFERENCES "channel_connections"("id") ON DELETE CASCADE,

  "sync_type" TEXT NOT NULL CHECK ("sync_type" IN (
    'inventory_push', 'rates_push', 'amenities_push',
    'reservations_pull', 'reservation_status_pull', 'webhook_received'
  )),

  "trigger_source" TEXT NOT NULL CHECK ("trigger_source" IN (
    'cron', 'manual', 'webhook', 'reservation_event'
  )),

  -- Time range synced (nullable for webhook receipts which are point-in-time)
  "start_date" DATE,
  "end_date" DATE,

  "records_processed" INTEGER NOT NULL DEFAULT 0,
  "records_succeeded" INTEGER NOT NULL DEFAULT 0,
  "records_failed" INTEGER NOT NULL DEFAULT 0,

  "status" TEXT NOT NULL CHECK ("status" IN (
    'pending', 'running', 'success', 'partial', 'failed'
  )),
  "error_message" TEXT,
  "error_details" JSONB,

  "duration_ms" INTEGER,
  "triggered_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "completed_at" TIMESTAMPTZ,

  -- Cost tracking — every external API call counts. Aggregated nightly
  -- by an existing usage-metrics cron (Stage 5.J). DryRun provider sets
  -- this to 0 so dev/demo activity doesn't pollute cost reports.
  "api_calls_count" INTEGER NOT NULL DEFAULT 0,

  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "channel_sync_log_connection_idx"
  ON "channel_sync_log"("channel_connection_id");
CREATE INDEX IF NOT EXISTS "channel_sync_log_status_idx"
  ON "channel_sync_log"("status");
CREATE INDEX IF NOT EXISTS "channel_sync_log_triggered_idx"
  ON "channel_sync_log"("triggered_at" DESC);
-- Composite for the integration health dashboard's per-connection
-- "last 50 attempts" panel.
CREATE INDEX IF NOT EXISTS "channel_sync_log_connection_triggered_idx"
  ON "channel_sync_log"("channel_connection_id", "triggered_at" DESC);

-- -----------------------------------------------------------------------------
-- 3) RLS — per-org isolation via is_in_user_organization() (Stage 5.J helper)
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  t TEXT;
BEGIN
  FOR t IN
    SELECT unnest(ARRAY['channel_connections', 'channel_sync_log'])
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format(
      'DROP POLICY IF EXISTS org_isolation ON %I; '
      'CREATE POLICY org_isolation ON %I FOR ALL '
      'USING (public.is_in_user_organization(organization_id)) '
      'WITH CHECK (public.is_in_user_organization(organization_id));',
      t, t
    );
  END LOOP;
END $$;

COMMIT;
