import { NextResponse } from "next/server";
import {
  getPortfolioMetrics,
  getTodaySchedule,
  getOperationalHealthTiles,
} from "@/features/dashboard/dashboard-cabinet-queries";
import { getLiveDashboardCounts } from "@/features/dashboard/live-counts";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * DONE-DEAD-BUTTONS — "Export brief" on the portfolio overview, wired to a
 * real Markdown download (replaces the ComingSoon "PDF coming soon" stub).
 *
 * A shareable daily brief built from the same live reads that back the
 * overview cabinet. Markdown is the honest, lossless format — it renders
 * in Slack / Notion / email and prints cleanly — without pulling in a PDF
 * engine. Lives under (dashboard) so enforceProductAccess("mgmt") gates it.
 */

const IDR_MILLION_MINOR = 1_000_000_00;

function idrM(minor: bigint): string {
  return `IDR ${(Number(minor) / IDR_MILLION_MINOR).toFixed(1)}M`;
}

export async function GET() {
  const [live, metrics, schedule, opsHealth] = await Promise.all([
    getLiveDashboardCounts().catch(() => null),
    getPortfolioMetrics().catch(() => null),
    getTodaySchedule().catch(() => []),
    getOperationalHealthTiles().catch(() => null),
  ]);

  const dateLabel = new Intl.DateTimeFormat("en-GB", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date());

  const arrivals = schedule.filter((s) => s.type === "arrival");
  const departures = schedule.filter((s) => s.type === "departure");

  const lines: string[] = [];
  lines.push(`# Daily portfolio brief`);
  lines.push(``);
  lines.push(`${dateLabel} · GMT+8`);
  lines.push(``);
  lines.push(`## Portfolio`);
  lines.push(`- Villas: ${live?.villas ?? 0}`);
  lines.push(`- Upcoming check-ins (14d): ${live?.upcomingCheckIns ?? 0}`);
  if (metrics) {
    lines.push(`- Occupancy YTD: ${metrics.occupancyYtd}%`);
    lines.push(`- ADR: ${idrM(metrics.adrIdrMinor)}`);
    lines.push(`- Net to owners (MTD): ${idrM(metrics.netToOwnersMtdIdrMinor)}`);
  }
  lines.push(``);
  lines.push(`## Today's schedule`);
  if (schedule.length === 0) {
    lines.push(`- No arrivals or departures scheduled today.`);
  } else {
    if (arrivals.length > 0) {
      lines.push(`### Arrivals (${arrivals.length})`);
      for (const a of arrivals) {
        lines.push(
          `- ${a.time} · ${a.villaCode} · ${a.guestName ?? "Guest"} · ${a.nights} night${a.nights === 1 ? "" : "s"}`,
        );
      }
    }
    if (departures.length > 0) {
      lines.push(`### Departures (${departures.length})`);
      for (const d of departures) {
        lines.push(`- ${d.time} · ${d.villaCode} · ${d.guestName ?? "Guest"}`);
      }
    }
  }
  lines.push(``);
  lines.push(`## Operational health`);
  if (opsHealth) {
    lines.push(`- Open maintenance tickets: ${opsHealth.openMaintenance}`);
    lines.push(`- Turnovers today: ${opsHealth.housekeepingTurnoversToday}`);
    lines.push(`- Owner-stay requests pending: ${opsHealth.ownerStayRequestsPending}`);
  } else {
    lines.push(`- No operational signals available.`);
  }
  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by Arconique OS · ${new Date().toISOString()}`);

  const body = lines.join("\n");
  const stamp = new Date().toISOString().slice(0, 10);
  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="daily-brief-${stamp}.md"`,
      "Cache-Control": "no-store",
    },
  });
}
