import { formatMoneyMinor } from "@/lib/money";
import type {
  OwnerStatementRow,
  StatementLineRow,
} from "@/features/finance/services";

/**
 * Deterministic, AI-free explanation of an owner statement. Reads the
 * already-allocated lines and derives a few human sentences that summarise
 * what's in the statement. Used in the owner portal under the "Why this
 * number" section and embedded in the PDF footer.
 */
export function generateStatementExplanation(
  statement: OwnerStatementRow,
  lines: StatementLineRow[],
): { headline: string; bullets: string[]; footer: string } {
  const fmt = (v: bigint) => formatMoneyMinor(v, statement.currency);
  const grouped = groupBy(lines, (l) => l.lineType);

  const revenueCount = (grouped.get("revenue") ?? []).length;
  const feeCount = (grouped.get("fee") ?? []).length;
  const expenseCount = (grouped.get("expense") ?? []).length;
  const taxCount = (grouped.get("tax") ?? []).length;
  const reserveCount = (grouped.get("reserve") ?? []).length;
  const mgmtCount = (grouped.get("management_fee") ?? []).length;

  const bullets: string[] = [];

  if (revenueCount > 0) {
    bullets.push(
      `Gross revenue of ${fmt(statement.grossRevenueMinor)} across ${revenueCount} recognised revenue line${revenueCount === 1 ? "" : "s"}.`,
    );
  } else {
    bullets.push("No recognised revenue lines fell inside this period.");
  }

  if (feeCount > 0) {
    const feeTopType = topCategory(grouped.get("fee") ?? []);
    bullets.push(
      `${fmt(statement.totalFeesMinor)} in channel and platform fees${feeTopType ? `, mostly ${feeTopType.replace(/_/g, " ")}` : ""}.`,
    );
  }

  if (expenseCount > 0) {
    const expenseTotal = sumLines(grouped.get("expense") ?? []);
    bullets.push(
      `${fmt(expenseTotal)} of operating expenses across ${expenseCount} cost line${expenseCount === 1 ? "" : "s"}.`,
    );
  }

  if (taxCount > 0) {
    bullets.push(`${fmt(statement.totalTaxesMinor)} in taxes (PHR / VAT / withholding).`);
  }

  if (reserveCount > 0) {
    bullets.push(
      `Reserve movement: ${fmt(statement.totalReservesMinor)} across ${reserveCount} contribution${reserveCount === 1 ? "" : "s"}.`,
    );
  }

  if (statement.managementFeeMinor !== 0n) {
    const ruleHint =
      mgmtCount > 0 ? "from posted management-fee lines" : "computed from the active management-fee rule";
    bullets.push(`Management fee ${fmt(statement.managementFeeMinor)} (${ruleHint}).`);
  }

  if (
    statement.occupancyRate !== null &&
    statement.adrMinor !== null &&
    statement.revparMinor !== null
  ) {
    bullets.push(
      `Occupancy ${(statement.occupancyRate * 100).toFixed(1)}%, ADR ${formatMoneyMinor(
        statement.adrMinor,
        statement.currency,
      )}, RevPAR ${formatMoneyMinor(statement.revparMinor, statement.currency)}.`,
    );
  }

  const headline =
    statement.netPayoutMinor >= 0n
      ? `Net owner payout for ${statement.periodLabel} is ${fmt(statement.netPayoutMinor)}.`
      : `This period closed with a deficit of ${fmt(-statement.netPayoutMinor)} carried forward.`;

  const footer =
    `Generated by Arconique Management OS · ` +
    `Statement code ${statement.statementCode} · ` +
    `Management model: ${statement.managementModel} · ` +
    `Every line traces to a source ledger row.`;

  return { headline, bullets, footer };
}

export function statementPdfFilename(s: OwnerStatementRow): string {
  return `Arconique-Statement-${s.statementCode}.pdf`;
}

function groupBy<T, K>(arr: T[], key: (item: T) => K): Map<K, T[]> {
  const m = new Map<K, T[]>();
  for (const it of arr) {
    const k = key(it);
    const list = m.get(k) ?? [];
    list.push(it);
    m.set(k, list);
  }
  return m;
}

function sumLines(lines: StatementLineRow[]): bigint {
  return lines.reduce<bigint>((acc, l) => acc + l.amountMinor, 0n);
}

function topCategory(lines: StatementLineRow[]): string | null {
  if (lines.length === 0) return null;
  const counts = new Map<string, number>();
  for (const l of lines) counts.set(l.category, (counts.get(l.category) ?? 0) + 1);
  let best: { cat: string; n: number } | null = null;
  for (const [cat, n] of counts) {
    if (!best || n > best.n) best = { cat, n };
  }
  return best?.cat ?? null;
}
