import {
  Briefcase,
  Building2,
  Calculator,
  CalendarRange,
  Camera,
  ClipboardList,
  Compass,
  FileCheck2,
  FileText,
  HandCoins,
  HardHat,
  KeyRound,
  LineChart,
  MapPinned,
  MessageSquareHeart,
  Package,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Truck,
  Wallet,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  Briefcase,
  Building2,
  Calculator,
  CalendarRange,
  Camera,
  ClipboardList,
  Compass,
  FileCheck2,
  FileText,
  HandCoins,
  HardHat,
  KeyRound,
  LineChart,
  MapPinned,
  MessageSquareHeart,
  Package,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Truck,
  Wallet,
};

export function resolveIcon(key: string): LucideIcon {
  return registry[key] ?? Building2;
}
