import { NextResponse } from "next/server";
import {
  getOperationsKpis,
  getMaintenanceTickets,
  getHousekeepingProgress,
} from "@/features/operations/operations-cabinet-queries";
import { listArrivals, listDepartures } from "@/features/front-office/services";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * DONE-DEAD-BUTTONS — "Brief team" on the Operations command center, wired
 * to a real Markdown download (replaces the ComingSoon stub).
 *
 * The daily team brief for housekeeping & maintenance: today's arrivals /
 * departures, the open maintenance queue sorted by priority, and the
 * housekeeping turnover workload. Markdown is the honest shareable format
 * (Slack / print / WhatsApp paste) without a PDF engine. Lives under
 * (dashboard) so enforceProductAccess("mgmt") gates access.
 */

const PRI_RANK: Record<string, number> = { p0: 0, p1: 1, p2: 2, p3: 3 };

export async function GET() {
  const today = new Date();
  const [kpis, tickets, housekeeping, arrivals, departures] = await Promise.all([
    getOperationsKpis().catch(() => null),
    getMaintenanceTickets(50).catch(() => []),
    getHousekeepingProgress().catch(() => []),
    listArrivals(today).catch(() => []),
    listDepartures(today).catch(() => []),
  ]);

  const dateLabel = today.toLocaleDateString("en-GB", {
    weekday: "long",
    day: "2-digit",
    month: "long",
    year: "numeric",
    timeZone: "Asia/Makassar",
  });

  const sortedTickets = [...tickets].sort(
    (a, b) =>
      (PRI_RANK[a.severity] ?? 9) - (PRI_RANK[b.severity] ?? 9) ||
      b.daysOpen - a.daysOpen,
  );

  const lines: string[] = [];
  lines.push(`# Operations team brief`);
  lines.push(``);
  lines.push(`${dateLabel} · WITA`);
  lines.push(``);
  lines.push(`## Today at a glance`);
  lines.push(`- Arrivals: ${arrivals.length}`);
  lines.push(`- Departures / turnovers: ${departures.length}`);
  lines.push(`- Open maintenance tickets: ${kpis?.ticketsOpen ?? tickets.length}`);
  lines.push(`- Housekeeping tasks scheduled: ${housekeeping.length}`);
  lines.push(``);

  lines.push(`## Arrivals`);
  if (arrivals.length === 0) {
    lines.push(`- None today.`);
  } else {
    for (const a of arrivals) {
      lines.push(
        `- ${a.villaCode ?? "—"} · ${a.guestDisplay} · ${a.guestsCount} pax`,
      );
    }
  }
  lines.push(``);

  lines.push(`## Departures`);
  if (departures.length === 0) {
    lines.push(`- None today.`);
  } else {
    for (const d of departures) {
      lines.push(`- ${d.villaCode ?? "—"} · ${d.guestDisplay}`);
    }
  }
  lines.push(``);

  lines.push(`## Maintenance queue (by priority)`);
  if (sortedTickets.length === 0) {
    lines.push(`- No open tickets.`);
  } else {
    for (const t of sortedTickets) {
      lines.push(
        `- [${t.severity.toUpperCase()}] ${t.title} · ${t.ticketCode} · ${t.villaCode ?? "—"} · ${t.status} · ${t.daysOpen}d open`,
      );
    }
  }
  lines.push(``);

  lines.push(`## Housekeeping / turnovers`);
  if (housekeeping.length === 0) {
    lines.push(`- No housekeeping tasks scheduled.`);
  } else {
    for (const h of housekeeping) {
      lines.push(
        `- ${h.villaCode} · ${h.status} · ${h.scheduledAt}${h.assigneeName ? ` · ${h.assigneeName}` : ""}`,
      );
    }
  }
  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by Arconique OS · ${new Date().toISOString()}`);

  const body = lines.join("\n");
  const stamp = today.toISOString().slice(0, 10);
  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="operations-brief-${stamp}.md"`,
      "Cache-Control": "no-store",
    },
  });
}
