// Pure permission table — safe to import from tests and client components.
// Server-only behaviour (auth + DB lookups) lives in `permissions.ts`.

export type RoleKey =
  | "super_admin"
  | "director"
  | "operations_manager"
  | "property_manager"
  | "booking_manager"
  | "revenue_manager"
  | "finance_manager"
  | "accountant"
  | "concierge"
  | "housekeeping_supervisor"
  | "housekeeper"
  | "technician"
  | "procurement_manager"
  | "security"
  | "sales_manager"
  | "investor_owner"
  | "investor_viewer"
  | "agent";

export const INTERNAL_ROLES: RoleKey[] = [
  "super_admin",
  "director",
  "operations_manager",
  "property_manager",
  "booking_manager",
  "revenue_manager",
  "finance_manager",
  "accountant",
  "concierge",
  "housekeeping_supervisor",
  "housekeeper",
  "technician",
  "procurement_manager",
  "security",
  "sales_manager",
];

// Roles that operate primarily through the field workflow. Listed separately
// so the permission rows below stay declarative.
const FIELD_OPS_ROLES: RoleKey[] = [
  "operations_manager",
  "property_manager",
  "housekeeping_supervisor",
  "housekeeper",
  "technician",
  "concierge",
];

export const ROLE_CAPABILITIES: Record<string, RoleKey[]> = {
  // identity / system
  "users.read": ["super_admin", "director"],
  "users.write": ["super_admin"],
  "roles.assign": ["super_admin"],
  // projects / villas
  "projects.read": INTERNAL_ROLES,
  "projects.write": ["super_admin", "director", "operations_manager", "property_manager"],
  "villas.read": INTERNAL_ROLES,
  "villas.write": ["super_admin", "director", "operations_manager", "property_manager"],
  // owners / shares
  "owners.read": ["super_admin", "director", "finance_manager", "accountant", "operations_manager"],
  "owners.write": ["super_admin", "director", "finance_manager"],
  "shares.read": ["super_admin", "director", "finance_manager", "accountant"],
  "shares.write": ["super_admin", "director", "finance_manager"],
  // crm follow-up tasks / reminders (any internal user can run their pipeline)
  "crm_tasks.read": INTERNAL_ROLES,
  "crm_tasks.write": INTERNAL_ROLES,
  // crm activity timeline — operators log notes/calls/emails on any record
  "crm_activity.write": INTERNAL_ROLES,
  // bookings / channels / guests
  "bookings.read": INTERNAL_ROLES,
  "bookings.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "channels.read": INTERNAL_ROLES,
  "channels.write": ["super_admin", "director", "operations_manager"],
  "guests.read": INTERNAL_ROLES,
  "guests.write": ["super_admin", "director", "operations_manager", "concierge"],
  // documents / audit
  "documents.read": INTERNAL_ROLES,
  "documents.write": ["super_admin", "director", "operations_manager", "finance_manager"],
  "audit.read": ["super_admin", "director"],
  // finance
  "finance.read": ["super_admin", "director", "finance_manager", "accountant", "operations_manager"],
  "finance.write": ["super_admin", "director", "finance_manager", "accountant"],
  "finance.close_period": ["super_admin", "director", "finance_manager"],
  "finance.issue_statement": ["super_admin", "director", "finance_manager"],
  "finance.approve_payout": ["super_admin", "director", "finance_manager"],
  "owner_statement.read": ["super_admin", "director", "finance_manager", "accountant"],
  "owner_statement.manage": ["super_admin", "director", "finance_manager"],
  // owner-portal access grants
  "owner_access.read": ["super_admin", "director", "finance_manager", "property_manager"],
  "owner_access.manage": ["super_admin", "director", "finance_manager"],
  // operations runtime
  "operations.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
    "concierge",
    "finance_manager",
    "accountant",
  ],
  "operations.write": FIELD_OPS_ROLES.concat(["super_admin", "director"]),
  "operations.assign": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
  ],
  "operations.approve": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
  ],
  // housekeeping
  "housekeeping.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
    "housekeeper",
  ],
  "housekeeping.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
    "housekeeper",
  ],
  // maintenance
  "maintenance.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "technician",
  ],
  "maintenance.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "technician",
  ],
  // service requests (internal — guest origination is handled separately)
  "service_request.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
    "housekeeping_supervisor",
  ],
  "service_request.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  // inventory + materials control (v5)
  "inventory.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
    "finance_manager",
    "accountant",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
  ],
  "inventory.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
  ],
  "inventory.adjust": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
  ],
  // procurement (v5)
  "procurement.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
    "finance_manager",
  ],
  "procurement.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
  ],
  "procurement.approve": [
    "super_admin",
    "director",
    "operations_manager",
    "procurement_manager",
    "finance_manager",
  ],
  // attachments (v5)
  "attachments.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
    "finance_manager",
    "accountant",
    "concierge",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
  ],
  "attachments.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
  ],
  // v6 — booking-channels integrations
  "integrations.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "finance_manager",
  ],
  "integrations.write": [
    "super_admin",
    "director",
    "operations_manager",
  ],
  "bookings.sync": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "bookings.conflict.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  // v6 — booking automation
  "automation.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
  ],
  "automation.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  // v6 — inventory counts (granular keys; existing inventory.* still applies)
  "inventory.count.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
    "housekeeping_supervisor",
    "finance_manager",
    "accountant",
  ],
  "inventory.count.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
    "housekeeping_supervisor",
  ],
  "inventory.count.approve": [
    "super_admin",
    "director",
    "operations_manager",
    "procurement_manager",
  ],
  // v6 — finance material-usage bridge
  "finance.bridge_material_usage": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  // v7 — background jobs / monitoring
  "jobs.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "finance_manager",
    "accountant",
    "procurement_manager",
  ],
  "jobs.run": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "finance_manager",
    "procurement_manager",
  ],
  "jobs.manage": [
    "super_admin",
    "director",
    "operations_manager",
  ],
  // v7 — notifications (no external delivery yet)
  "notifications.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "finance_manager",
    "accountant",
    "procurement_manager",
    "housekeeping_supervisor",
    "concierge",
  ],
  "notifications.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "notifications.manage": [
    "super_admin",
    "director",
    "operations_manager",
  ],
  // v8B — AI Operations Co-pilot (read-only)
  "ai.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "finance_manager",
    "housekeeping_supervisor",
  ],
  "ai.run": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "ai.manage": [
    "super_admin",
    "director",
    "operations_manager",
  ],
  // v9A — availability, front office, readiness, scopes, security registry.
  "availability.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
    "security",
    "finance_manager",
    "accountant",
  ],
  "availability.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "front_office.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "housekeeping_supervisor",
    "security",
  ],
  "front_office.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "readiness.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
  ],
  "readiness.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
  ],
  "responsibility_scopes.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
  ],
  "responsibility_scopes.manage": [
    "super_admin",
    "director",
    "operations_manager",
  ],
  "security.read": [
    "super_admin",
    "director",
    "operations_manager",
    "security",
  ],
  "security.manage": ["super_admin", "director", "operations_manager"],
  // v9B — owner stays + relocation + basic pricing.
  "owner_stay.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "finance_manager",
    "accountant",
    "investor_owner",
    "investor_viewer",
  ],
  "owner_stay.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "investor_owner",
  ],
  "owner_stay.approve": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "owner_stay.relocate": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "pricing.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "finance_manager",
    "accountant",
  ],
  "pricing.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "relocation.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "relocation.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  // v9C — finance bridge + public quote API.
  "owner_stay.finance_bridge": [
    "super_admin",
    "director",
    "finance_manager",
    "operations_manager",
    "property_manager",
  ],
  "quote.read_public": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "finance_manager",
    "accountant",
  ],
  // v9D — preventive maintenance intelligence + utilities + risk feed.
  "maintenance_intelligence.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "housekeeping_supervisor",
    "technician",
    "procurement_manager",
    "finance_manager",
    "accountant",
  ],
  "maintenance_intelligence.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "technician",
  ],
  "maintenance_intelligence.generate": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "utilities.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
    "finance_manager",
    "accountant",
    "technician",
  ],
  "utilities.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "procurement_manager",
    "technician",
  ],
  "utilities.pay": [
    "super_admin",
    "director",
    "operations_manager",
    "finance_manager",
  ],
  "maintenance_risk.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "housekeeping_supervisor",
    "finance_manager",
  ],
  "maintenance_risk.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  // v9E — guest stay tokens, villa guides, smart-lock stub.
  "guest_stay.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "housekeeping_supervisor",
  ],
  "guest_stay.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "guest_stay.token.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "villa_guide.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "housekeeping_supervisor",
    "housekeeper",
    "technician",
  ],
  "villa_guide.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "smart_lock.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "security",
  ],
  "smart_lock.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "security",
  ],
  // v9F — guest services catalog + upsell orders + concierge fulfilment +
  // guest-service revenue foundation.
  "guest_services.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "finance_manager",
    "housekeeping_supervisor",
  ],
  "guest_services.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "guest_services.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "guest_service_orders.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "finance_manager",
    "housekeeping_supervisor",
  ],
  "guest_service_orders.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "guest_service_orders.fulfill": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
    "housekeeping_supervisor",
  ],
  "guest_service_orders.finance_bridge": [
    "super_admin",
    "director",
    "operations_manager",
    "finance_manager",
  ],
  // v9G — guest stay security keys.
  "guest_stay_security.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "security",
  ],
  "guest_stay_security.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "security",
  ],
  "guest_stay_verification.issue": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "wifi_credentials.encrypt": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "wifi_credentials.rotate": [
    "super_admin",
    "director",
    "operations_manager",
  ],
  // v9H — guest AI concierge (read-only).
  "guest_ai.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "guest_ai.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  // v9I — guest AI concierge operational handoff.
  "guest_ai.handoff.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
    "booking_manager",
  ],
  "guest_ai.handoff.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  // v9K — internal-note + attachment fine-grained permissions.
  "guest_ai.handoff.notes.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "guest_ai.handoff.attachments.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
    "booking_manager",
  ],
  "guest_ai.handoff.attachments.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  // Prompt 101 — Owner intelligence portal.
  "owner_calendar.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "finance_manager",
    "concierge",
    "investor_owner",
    "investor_viewer",
  ],
  "owner_calendar.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "villa_health.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "finance_manager",
    "concierge",
    "investor_owner",
    "investor_viewer",
  ],
  "villa_health.generate": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "guest_review.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "finance_manager",
    "concierge",
    "investor_owner",
    "investor_viewer",
  ],
  "guest_review.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "guest_review.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  // Prompt 102 — Guest journey automation.
  "guest_journey.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "guest_journey.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "guest_journey.run": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "guest_journey.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "review_request.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "review_request.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  // Prompt 103 — Service fulfilment & vendor ops.
  "service_vendor.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "finance_manager",
    "accountant",
  ],
  "service_vendor.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  "service_fulfilment.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "finance_manager",
    "accountant",
  ],
  "service_fulfilment.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "service_fulfilment.dispatch": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "service_fulfilment.finance_bridge": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  "service_invoice.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "finance_manager",
    "accountant",
  ],
  "service_invoice.write": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  "service_rating.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "concierge",
  ],
  "service_rating.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
  ],
  // Prompt 104 — Dynamic pricing & availability rules.
  "dynamic_pricing.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
    "finance_manager",
    "accountant",
  ],
  "dynamic_pricing.write": [
    "super_admin",
    "director",
    "operations_manager",
    "revenue_manager",
  ],
  "dynamic_pricing.manage": [
    "super_admin",
    "director",
    "revenue_manager",
  ],
  "pricing_quote.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
    "finance_manager",
  ],
  "pricing_channel_push.simulate": [
    "super_admin",
    "director",
    "revenue_manager",
    "operations_manager",
  ],
  // Prompt 105 — Direct booking hold & checkout stub.
  "direct_booking.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
    "concierge",
    "finance_manager",
    "accountant",
  ],
  "direct_booking.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "direct_booking.approve": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "direct_booking.convert": [
    "super_admin",
    "director",
    "booking_manager",
  ],
  "direct_booking.manage": [
    "super_admin",
    "director",
    "booking_manager",
  ],
  // Prompt 106 — Payments + deposit workflow.
  "payments.read": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "payments.write": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  "payments.manage": [
    "super_admin",
    "director",
    "finance_manager",
  ],
  "direct_booking.deposit.read": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "direct_booking.deposit.write": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "booking_manager",
  ],
  "direct_booking.deposit.mark_paid": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  "direct_booking.deposit.refund": [
    "super_admin",
    "director",
    "finance_manager",
  ],
  // Prompt 107 — Direct booking finance reconciliation + deposit expiry.
  "direct_booking.reconcile.read": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
  ],
  "direct_booking.reconcile.write": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  "direct_booking.reconcile.reverse": [
    "super_admin",
    "director",
    "finance_manager",
  ],
  "direct_booking.deposit.expire": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "booking_manager",
  ],
  // Prompt 108 — Owner booking projection + owner revenue transparency.
  "owner_booking.read": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
    "investor_owner",
    "investor_viewer",
  ],
  "owner_booking.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
  ],
  "owner_revenue.read": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
    "investor_owner",
    "investor_viewer",
  ],
  "owner_revenue.manage": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "revenue_manager",
  ],
  // Prompt 109 — Guest booking notifications + status center.
  "direct_booking.guest_notifications.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
    "finance_manager",
    "accountant",
  ],
  "direct_booking.guest_notifications.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "direct_booking.guest_messages.read": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "direct_booking.guest_messages.write": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "concierge",
  ],
  "direct_booking.guest_messages.manage": [
    "super_admin",
    "director",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  // Prompt 110 — Finance & statement transparency final polish.
  "statement_transparency.read": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
    "investor_owner",
    "investor_viewer",
  ],
  "statement_transparency.manage": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  "statement_reconciliation.read": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
    "operations_manager",
    "property_manager",
    "booking_manager",
    "revenue_manager",
  ],
  "statement_reconciliation.manage": [
    "super_admin",
    "director",
    "finance_manager",
    "accountant",
  ],
  // Prompt 111 — Security baseline & operational hardening.
  // (`security.*` is reserved for the camera registry; we use
  // `auth_security.*` for the auth/login/MFA admin surface.)
  "auth_security.read": [
    "super_admin",
    "director",
    "finance_manager",
    "operations_manager",
    "property_manager",
  ],
  "auth_security.manage": ["super_admin", "director"],
  "mfa.manage": ["super_admin", "director"],
  "login_attempt.read": [
    "super_admin",
    "director",
    "finance_manager",
    "operations_manager",
    "property_manager",
  ],
  "job_lock.read": [
    "super_admin",
    "director",
    "finance_manager",
    "operations_manager",
    "property_manager",
  ],
  "job_lock.manage": ["super_admin", "director"],
  "system_health.read": [
    "super_admin",
    "director",
    "finance_manager",
    "operations_manager",
    "property_manager",
    "booking_manager",
  ],
  "system_health.manage": ["super_admin", "director"],
  // System & platform cabinet (jobs, deployment, storage, health). Gated to
  // platform operators only — these surfaces expose cross-tenant catalog
  // stats (pg_stat_user_tables row counts, env readiness, cron config) that
  // cannot be org-filtered, so only super_admin / director may reach them.
  "system.read": ["super_admin", "director"],
};

export interface CurrentUserContext {
  mode: "live" | "demo";
  appUser: {
    id: string;
    email: string;
    fullName: string;
    status: string;
    organizationId: string;
  } | null;
  roles: RoleKey[];
  isInternal: boolean;
  isSuperAdmin: boolean;
}

export function hasPermission(ctx: CurrentUserContext, permission: string): boolean {
  if (ctx.mode === "demo") return true;
  if (ctx.isSuperAdmin) return true;
  const allowed = ROLE_CAPABILITIES[permission];
  if (!allowed) return false;
  return ctx.roles.some((r) => allowed.includes(r));
}
