import Link from "next/link";
import { Section } from "@/components/ui/section";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { OperationsCopilotRefreshButton } from "./operations-copilot-refresh-button";
import { getLatestOperationsSummary } from "@/features/ai/operations-copilot/service";
import { isAiConfigured, isAiDryRun } from "@/lib/env";

const RISK_TONES: Record<string, "neutral" | "info" | "warning" | "danger" | "success"> = {
  normal: "success",
  elevated: "warning",
  high: "danger",
};

export async function OperationsCopilotCard() {
  const summary = await getLatestOperationsSummary();
  const aiActive = isAiConfigured() && !isAiDryRun();

  return (
    <Section
      eyebrow="AI Operations Co-pilot"
      title="Daily briefing"
      description={
        aiActive
          ? "Generated by Claude Sonnet via the read-only tool allowlist. Refresh re-runs the model against the current snapshot."
          : "AI key not configured (or AI_DRY_RUN=1) — showing a deterministic fallback derived directly from the operations snapshot. Set ANTHROPIC_API_KEY and AI_DRY_RUN=0 to enable Claude."
      }
    >
      {!summary ? (
        <div className="rounded-md border border-dashed border-line-soft bg-muted/20 p-6 text-sm text-ink-tertiary flex items-center justify-between gap-4">
          <span>No briefing yet. Click refresh to generate the first one.</span>
          <OperationsCopilotRefreshButton />
        </div>
      ) : (
        <div className="rounded-md border border-line-soft bg-surface p-5 md:p-6">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div className="min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <Badge tone={RISK_TONES[summary.riskLevel] ?? "neutral"}>
                  Risk: {summary.riskLevel}
                </Badge>
                {!aiActive && <Badge tone="neutral">fallback</Badge>}
                <span className="text-[11px] text-ink-tertiary tabular-nums">
                  {summary.createdAt.slice(0, 16).replace("T", " ")}
                </span>
              </div>
              <h3 className="text-ink font-medium text-base mt-2">
                {summary.title}
              </h3>
              <p className="text-sm text-ink-secondary mt-2 leading-relaxed whitespace-pre-line">
                {summary.executiveSummary}
              </p>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              <Button asChild size="sm" variant="secondary">
                <Link href="/dashboard/ai/operations">View detail</Link>
              </Button>
              <OperationsCopilotRefreshButton />
            </div>
          </div>

          {(summary.risks.length > 0 ||
            summary.recommendedActions.length > 0) && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-5">
              {summary.risks.length > 0 && (
                <div>
                  <div className="text-[11px] uppercase tracking-widest text-ink-tertiary mb-2">
                    Risks
                  </div>
                  <ul className="text-sm text-ink-secondary space-y-1.5">
                    {summary.risks.slice(0, 4).map((r, i) => (
                      <li key={i} className="flex gap-2">
                        <span className="text-ink">•</span>
                        <span>
                          <span className="text-ink">{r.title}</span>
                          {r.detail ? (
                            <span className="text-ink-tertiary"> — {r.detail}</span>
                          ) : null}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              {summary.recommendedActions.length > 0 && (
                <div>
                  <div className="text-[11px] uppercase tracking-widest text-ink-tertiary mb-2">
                    Suggested actions
                  </div>
                  <ul className="text-sm text-ink-secondary space-y-1.5">
                    {summary.recommendedActions.slice(0, 4).map((a, i) => (
                      <li key={i} className="flex gap-2">
                        <span className="text-ink">•</span>
                        <span>
                          <span className="text-ink">{a.title}</span>
                          {a.detail ? (
                            <span className="text-ink-tertiary"> — {a.detail}</span>
                          ) : null}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </Section>
  );
}
