/**
 * Stage 8 / Phase 0 — create the audit-bot Supabase Auth user and emit
 * its credentials to `.env.audit.local` (gitignored).
 *
 * Idempotent: if the user already exists in Supabase Auth, it patches
 * the password to a freshly-generated one and reports the existing
 * UUID so a subsequent `bootstrap-admin.ts` run can link it.
 *
 * Usage (loads env from .env.production.local automatically):
 *   node --env-file=.env.production.local --import tsx scripts/create-audit-bot.ts
 *
 * Output: writes UUID + email + password to .env.audit.local
 *
 * Required env:
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 */

import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const EMAIL = process.env.AUDIT_BOT_EMAIL ?? "audit-bot@arconique.com";

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY — did you load .env.production.local?",
  );
  process.exit(1);
}

const ADMIN_BASE = `${SUPABASE_URL.replace(/\/$/, "")}/auth/v1/admin`;

function generatePassword(): string {
  // 24 random URL-safe bytes → ~32 chars; passes Supabase password rules.
  return randomBytes(24).toString("base64url");
}

async function findUserByEmail(email: string): Promise<{ id: string } | null> {
  const url = `${ADMIN_BASE}/users?email=${encodeURIComponent(email)}`;
  const resp = await fetch(url, {
    headers: {
      apikey: SERVICE_KEY!,
      authorization: `Bearer ${SERVICE_KEY!}`,
    },
  });
  if (!resp.ok) {
    throw new Error(`list users: ${resp.status} ${await resp.text()}`);
  }
  const body = (await resp.json()) as { users?: Array<{ id: string; email?: string }> };
  // Supabase's list endpoint returns paginated users, not filtered by email.
  // Filter client-side by exact email match.
  const found = (body.users ?? []).find((u) => u.email?.toLowerCase() === email.toLowerCase());
  return found ? { id: found.id } : null;
}

async function createUser(email: string, password: string): Promise<{ id: string }> {
  const resp = await fetch(`${ADMIN_BASE}/users`, {
    method: "POST",
    headers: {
      apikey: SERVICE_KEY!,
      authorization: `Bearer ${SERVICE_KEY!}`,
      "content-type": "application/json",
    },
    body: JSON.stringify({
      email,
      password,
      email_confirm: true,
      user_metadata: {
        full_name: "Audit Bot",
        purpose: "Stage 8 production audit harness",
      },
    }),
  });
  if (!resp.ok) {
    throw new Error(`create user: ${resp.status} ${await resp.text()}`);
  }
  const body = (await resp.json()) as { id: string };
  return { id: body.id };
}

async function patchPassword(userId: string, password: string): Promise<void> {
  const resp = await fetch(`${ADMIN_BASE}/users/${userId}`, {
    method: "PUT",
    headers: {
      apikey: SERVICE_KEY!,
      authorization: `Bearer ${SERVICE_KEY!}`,
      "content-type": "application/json",
    },
    body: JSON.stringify({ password }),
  });
  if (!resp.ok) {
    throw new Error(`patch password: ${resp.status} ${await resp.text()}`);
  }
}

async function main(): Promise<void> {
  const password = generatePassword();
  let userId: string;

  const existing = await findUserByEmail(EMAIL);
  if (existing) {
    console.log(`[audit-bot] auth user already exists (id=${existing.id}); rotating password`);
    await patchPassword(existing.id, password);
    userId = existing.id;
  } else {
    console.log(`[audit-bot] creating new auth user for ${EMAIL}`);
    const created = await createUser(EMAIL, password);
    userId = created.id;
    console.log(`[audit-bot] created auth user id=${userId}`);
  }

  const envPath = resolve(process.cwd(), ".env.audit.local");
  const lines = [
    "# Stage 8 / Phase 0 — audit-bot credentials",
    "# Auto-generated by scripts/create-audit-bot.ts",
    "# DO NOT commit (matched by `.env*.local` in .gitignore)",
    "",
    `AUDIT_BOT_EMAIL=${EMAIL}`,
    `AUDIT_BOT_PASSWORD=${password}`,
    `AUDIT_BOT_AUTH_USER_ID=${userId}`,
    "",
  ].join("\n");
  writeFileSync(envPath, lines, { mode: 0o600 });
  console.log(`[audit-bot] wrote ${envPath} (mode 0600)`);
  console.log(`[audit-bot] next step: run bootstrap-admin to link as super_admin:`);
  console.log(
    `  AUTH_USER_ID=${userId} EMAIL=${EMAIL} FULL_NAME='Audit Bot' \\`,
  );
  console.log(
    `    ADMIN_BOOTSTRAP_SECRET="$ADMIN_BOOTSTRAP_SECRET" \\`,
  );
  console.log(`    npx tsx scripts/bootstrap-admin.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
