import type { Metadata } from "next";
import Link from "next/link";
import { EmptyState } from "@/components/ui/empty-state";
import { Card, HandoffBadge } from "@/components/dashboard/primitives";
import { DevelopmentShell } from "@/components/development/development-shell";
import { requireOrgId } from "@/features/auth/require-org";
import { listExportRequestsForOrg } from "@/lib/development/server/data-export/data-export-actions";
import { safeQuery } from "@/lib/development/safe-query";

export const metadata: Metadata = { title: "Data export · Settings" };
export const dynamic = "force-dynamic";

const STATUS_TONES: Record<string, "ok" | "warn" | "danger" | "soft"> = {
  pending: "soft",
  processing: "warn",
  completed: "ok",
  failed: "danger",
};

export default async function DataExportPage() {
  const orgId = await requireOrgId();
  const requests = await safeQuery(
    "settings-data-export.listExportRequestsForOrg",
    listExportRequestsForOrg(orgId),
    [] as Awaited<ReturnType<typeof listExportRequestsForOrg>>,
  );

  return (
    <DevelopmentShell>
      <div className="page-header">
        <div className="left">
          <div className="crumb">
            <Link href="/development-os">Development OS</Link> /{" "}
            <span>Settings</span> / <span>Data export</span>
          </div>
          <h1>Data export</h1>
          <p className="text-[13px] text-ink-3 mt-2 max-w-[680px]">
            GDPR-compliant per-organization snapshots. Output is generated by
            the dev_os_data_export_processor cron and stays available for 7
            days.
          </p>
        </div>
      </div>

      <div>
        <div className="label mb-2.5">{requests.length} export request(s)</div>
        {requests.length === 0 ? (
          <Card padding="default">
            <EmptyState
              title="No export requests"
              description="Use the requestDataExport server action to enqueue one."
            />
          </Card>
        ) : (
          <Card padding="none" overflowHidden>
            <table className="data">
              <thead>
                <tr>
                  <th scope="col">Requested</th>
                  <th scope="col">Scope</th>
                  <th scope="col">Format</th>
                  <th scope="col" className="num">Size</th>
                  <th scope="col">Expires</th>
                  <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
                {requests.map((r) => (
                  <tr key={r.id}>
                    <td className="text-xs text-ink-3">
                      {new Date(r.requestedAt).toLocaleString()}
                    </td>
                    <td className="text-xs">{r.exportScope}</td>
                    <td className="text-xs">{r.exportFormat}</td>
                    <td className="num mono text-xs">
                      {r.outputSizeBytes ? Number(r.outputSizeBytes).toLocaleString() : "—"}
                    </td>
                    <td className="text-xs text-ink-3">
                      {r.downloadExpiresAt
                        ? new Date(r.downloadExpiresAt).toLocaleDateString()
                        : "—"}
                    </td>
                    <td>
                      <HandoffBadge tone={STATUS_TONES[r.status] ?? "soft"}>
                        {r.status}
                      </HandoffBadge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        )}
      </div>
    </DevelopmentShell>
  );
}
