import type { Metadata } from "next";
import { PageHeader } from "@/components/ui/page-header";
import { Section } from "@/components/ui/section";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { DevelopmentShell } from "@/components/development/development-shell";
import { requireOrgId } from "@/features/auth/require-org";
import { listExportRequestsForOrg } from "@/lib/development/server/data-export/data-export-actions";
import { safeQuery } from "@/lib/development/safe-query";

export const metadata: Metadata = { title: "Data export · Settings" };
export const dynamic = "force-dynamic";

const STATUS_TONES: Record<string, "success" | "warning" | "danger" | "neutral"> = {
  pending: "neutral",
  processing: "warning",
  completed: "success",
  failed: "danger",
};

export default async function DataExportPage() {
  const orgId = await requireOrgId();
  const requests = await safeQuery(
    "settings-data-export.listExportRequestsForOrg",
    listExportRequestsForOrg(orgId),
    [] as Awaited<ReturnType<typeof listExportRequestsForOrg>>,
  );

  return (
    <DevelopmentShell>
      <PageHeader
        title="Data export"
        breadcrumbs={[
          { label: "Development OS", href: "/development-os" },
          { label: "Settings" },
          { label: "Data export" },
        ]}
        description="GDPR-compliant per-organization snapshots. Output is generated by the dev_os_data_export_processor cron and stays available for 7 days."
      />

      <Section title={`${requests.length} export request(s)`}>
        {requests.length === 0 ? (
          <EmptyState
            title="No export requests"
            description="Use the requestDataExport server action to enqueue one."
          />
        ) : (
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="text-left text-ink-tertiary border-b border-line-soft">
                <th className="py-2">Requested</th>
                <th>Scope</th>
                <th>Format</th>
                <th>Size</th>
                <th>Expires</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {requests.map((r) => (
                <tr key={r.id} className="border-b border-line-soft">
                  <td className="py-2 text-xs text-ink-tertiary">
                    {new Date(r.requestedAt).toLocaleString()}
                  </td>
                  <td className="text-xs">{r.exportScope}</td>
                  <td className="text-xs">{r.exportFormat}</td>
                  <td className="font-mono tabular-nums text-xs">
                    {r.outputSizeBytes ? Number(r.outputSizeBytes).toLocaleString() : "—"}
                  </td>
                  <td className="text-xs text-ink-tertiary">
                    {r.downloadExpiresAt
                      ? new Date(r.downloadExpiresAt).toLocaleDateString()
                      : "—"}
                  </td>
                  <td>
                    <Badge tone={STATUS_TONES[r.status] ?? "neutral"}>
                      {r.status}
                    </Badge>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Section>
    </DevelopmentShell>
  );
}
