import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Section } from "@/components/ui/section";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { Table, THead, TBody, TR, TH, TD, TDNum } from "@/components/ui/table";
import { DevelopmentShell } from "@/components/development/development-shell";
import { getDb } from "@/lib/db/client";
import {
  listTaxPeriodReports,
  listAllTaxTypes,
} from "@/lib/development/server/tax/tax-actions";
import { safeQuery } from "@/lib/development/safe-query";
import { FinalizeReportButton } from "./_finalize-button";

export const metadata: Metadata = {
  title: "Tax reports · Development OS",
};
export const dynamic = "force-dynamic";

const STATUS_TONE: Record<string, "info" | "success" | "warning" | "neutral"> = {
  draft: "neutral",
  finalized: "info",
  submitted: "success",
  amended: "warning",
  archived: "neutral",
};

export default async function TaxReportsListPage() {
  const db = getDb();
  if (!db) {
    return (
      <DevelopmentShell>
        <PageHeader title="Tax reports" />
        <EmptyState title="Database not configured" description="Set DATABASE_URL." />
      </DevelopmentShell>
    );
  }
  const [reports, taxTypes] = await Promise.all([
    safeQuery("listTaxPeriodReports", listTaxPeriodReports(), [], 4000),
    safeQuery("listAllTaxTypes", listAllTaxTypes(), [], 4000),
  ]);
  const taxTypeBy = new Map(taxTypes.map((t) => [t.id, t]));

  return (
    <DevelopmentShell>
      <PageHeader
        breadcrumbs={[
          { label: "Development OS", href: "/development-os" },
          { label: "Finance", href: "/development-os/finance" },
          { label: "Tax reports" },
        ]}
        eyebrow={`${reports.length} report${reports.length === 1 ? "" : "s"}`}
        title="Tax period reports"
        description="Generated by the monthly dev_os_tax_period_report cron (UPSERT on tax_type × period_start × period_end). Operator finalises manually after review. Use the unclassified inbox to clear pending transactions before finalising."
        actions={
          <Button asChild variant="secondary">
            <Link href="/development-os/finance">
              <ArrowLeft className="w-4 h-4" strokeWidth={1.75} />
              Finance
            </Link>
          </Button>
        }
      />

      {reports.length === 0 ? (
        <EmptyState
          title="No tax reports yet"
          description="The monthly dev_os_tax_period_report cron generates reports on the 1st of each month. You can also run generateTaxPeriodReport manually for any (tax_type, period) pair."
        />
      ) : (
        <Section eyebrow="Catalog" title="All tax period reports (most recent first)">
          <Table>
            <THead>
              <TR>
                <TH>Tax type</TH>
                <TH>Period</TH>
                <TH>Taxable amount</TH>
                <TH>Tax amount</TH>
                <TH>Txns</TH>
                <TH>Unclassified</TH>
                <TH>Status</TH>
                <TH>Finalized</TH>
                <TH>Actions</TH>
              </TR>
            </THead>
            <TBody>
              {reports.map((r) => {
                const tt = taxTypeBy.get(r.taxTypeId);
                return (
                  <TR key={r.id}>
                    <TD className="text-sm">
                      {tt?.displayName ?? r.taxTypeId.slice(0, 8)}
                    </TD>
                    <TD className="text-xs">
                      {r.periodStart} → {r.periodEnd}
                    </TD>
                    <TDNum>
                      $
                      {(Number(r.totalTaxableAmountMinor) / 100).toLocaleString()}
                    </TDNum>
                    <TDNum>
                      $
                      {(Number(r.totalTaxAmountMinor) / 100).toLocaleString()}
                    </TDNum>
                    <TDNum>{r.transactionCount}</TDNum>
                    <TDNum
                      className={
                        r.unclassifiedTransactionCount > 0 ? "text-warning" : ""
                      }
                    >
                      {r.unclassifiedTransactionCount}
                    </TDNum>
                    <TD>
                      <Badge tone={STATUS_TONE[r.status] ?? "neutral"}>
                        {r.status}
                      </Badge>
                    </TD>
                    <TD className="text-xs">
                      {r.finalizedAt
                        ? new Date(r.finalizedAt).toISOString().slice(0, 10)
                        : "—"}
                    </TD>
                    <TD>
                      <FinalizeReportButton
                        id={r.id}
                        status={r.status}
                        unclassifiedCount={r.unclassifiedTransactionCount}
                      />
                    </TD>
                  </TR>
                );
              })}
            </TBody>
          </Table>
        </Section>
      )}
    </DevelopmentShell>
  );
}
